spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    password: root

#mybatis:
# typeAliasesPackage: com.lc.entity
# mapperLocations:   , classpath:/com/mapper/*.xml


mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:/mapper/*.xml,/com/lc/mapper/xml/*.xml
  typeAliasesPackage: com.lc.entity
#  - classpath:/mapper/*.xml
#  - classpath*:/com/lc/mapper/xml/*.xml
